
  INSERT INTO "AZ_TEST.DB".AZ_TEST.CATEGORY (ID,NAMECATEGORY) VALUES (1,'Fruits');
  INSERT INTO "AZ_TEST.DB".AZ_TEST.CATEGORY (ID,NAMECATEGORY) VALUES (2,'Juices');
	INSERT INTO "AZ_TEST.DB".AZ_TEST.ITEM (ID,ARTICLE,CATEGORY_ID,NAMEITEM,KOLVO,PRICE)
	VALUES (25,24,1,'Apples',3,48);
	INSERT INTO "AZ_TEST.DB".AZ_TEST.ITEM (ID,ARTICLE,CATEGORY_ID,NAMEITEM,KOLVO,PRICE)
	VALUES (22,29,1,'Plums',8,12);
	INSERT INTO "AZ_TEST.DB".AZ_TEST.ITEM (ID,ARTICLE,CATEGORY_ID,NAMEITEM,KOLVO,PRICE)
	VALUES (21,28,2,'Tomat',4,100);
	INSERT INTO "AZ_TEST.DB".AZ_TEST.ITEM (ID,ARTICLE,CATEGORY_ID,NAMEITEM,KOLVO,PRICE)
	VALUES (24,12,2,'Grape',2,120);